name: OpenTofu plan

on:
  pull_request:
    paths:
      - 'tofu/**'
      - 'UnregisteredAzureWebsitesDomains.json'
      - '.github/workflows/tofu-plan.yml'
      - '.github/workflows/tofu-apply.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: tofu-plan-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PLAN }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: tofu plan
        uses: dflook/tofu-plan@c7416238983bdd94c5486fb856bb7358f2bcc935 # v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: tofu
          backend_config: |
            resource_group_name=${{ secrets.TFSTATE_RESOURCE_GROUP }}
            storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}
            container_name=${{ secrets.TFSTATE_CONTAINER }}
            key=${{ secrets.TFSTATE_KEY }}
